# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MaternFun <- function(distmat, covparms) {
    .Call('aldodevel_MaternFun', PACKAGE = 'aldodevel', distmat, covparms)
}

OrderedCompLik <- function(covparms, y, locs, NNarray) {
    .Call('aldodevel_OrderedCompLik', PACKAGE = 'aldodevel', covparms, y, locs, NNarray)
}

